kind: pipeline
name: release

steps:
  - name: autotag
    image: node
    environment:
      GIT_USER:
        from_secret: GITHUB_USERNAME
      GIT_SECRET:
        from_secret: GITHUB_KEY
    commands:
      - npm install -g @author.io/cicd-autotag
      - autotag
    when:
      event:
        - push
  - name: build
    image: node
    commands:
      - npm install
      - npm run build
    when:
      event:
        - tag
  - name: github_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files: dist/**/*
    when:
      event:
        - tag
  - name: npm_release
    image: plugins/npm
    settings:
      username:
        from_secret: NPM_USERNAME
      password:
        from_secret: NPM_PASSWORD
      email:
        from_secret: NPM_EMAIL
      registry: "https://registry.npmjs.org"
    when:
      event:
        - tag
  - name: notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: releases
      icon_url: https://avatars0.githubusercontent.com/u/46585558?s=32
      template: >
        Release <a href="https://github.com/{{repo.owner}}/{{repo.name}}/releases/tag/{{build.tag}}">{{build.tag}}</a> (build <a href="{{build.link}}">{{build.number}}</a>){{#success build.status}}succeeded{{else}}failed{{/success}}.
        {{#success build.status}}
          <b>Availability:</b>
          <li>CDN: <a href="https://cdn.author.io/{{repo.owner}}/{{repo.name}}/{{build.tag}}/author-{{repo.name}}.js">https://cdn.author.io/{{repo.owner}}/{{repo.name}}/{{build.tag}}/author-{{repo.name}}.js</a></li>
          <li>npm: `npm install @author.io/elment-base@{{build.tag}}`</li>
        {{/success}}
    when:
      event:
        - tag
