kind: pipeline
name: release

steps:
  - name: autotag
    image: node
    environment:
      GIT_USER:
        from_secret: GITHUB_USERNAME
      GIT_SECRET:
        from_secret: GITHUB_KEY
    commands:
      - npm install -g @author.io/cicd-autotag
      - autotag
    when:
      event:
        - push
  - name: build
    image: node
    commands:
      - npm install
      - npm run build
    when:
      event:
        - tag
  - name: github_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files: dist/**/*
    when:
      event:
        - tag
  - name: npm_release
    image: plugins/npm
    settings:
      username:
        from_secret: NPM_USERNAME
      password:
        from_secret: NPM_PASSWORD
      email:
        from_secret: NPM_EMAIL
      registry: "https://registry.npmjs.org"
    when:
      event:
        - tag
  - name: notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: releases
      icon_url: https://avatars0.githubusercontent.com/u/46585558?s=32
      template: >
        {{#success build.status}}
          Release {{build.tag}} (build {{build.number}}) succeeded.
        {{else}}
          Release {{build.tag}} (build {{build.number}}) failed.
        {{/success}}
    when:
      event:
        - tag
