language: node_js
node_js:
- 11.6.0
addons:
  browserstack:
    username: $BROWSER_STACK_USERNAME
    access_key:
      secure: "pFd4xp9HRDdUjeFVT72DcxJl2iCaYJE9sQYiiQ6tZjK+Z3Dabt1JH97Ogycmj0PPoVNWVPjKyRuc31LwkdmtD7x48fTrJ3yXk8RIfPHneSi89+p9SU4EEq6Ss+/f1z8WHH0nauXCmvQ9vsghzIfN+LgeBVHc7fl4vQbJuTGma5x4l6+kdvyrLPMzuQrNUS3Uapd1ebCmHBhv3t6tOcDwYTaHPlFjWxjapDSRrDGdSgryzlZw+saPKw+LrsnA2eMC7CLQa9OVxVb7j1REIWSlhoF/BtgfQgpIQV/mmdjxaNp5q8Xm09NVX/8PWzI7/3CZySD/dQAF2KjP9qarU7zeeRhxWZuccsR23x+p8UypCHVs9geXWKmmaK61zdeJ1wEKviuuJGWuponhJR26p8sALmxQzVD/HHqSI5mZY2sYegcssPyYWH0eJvVfsL6Qd1uUhCub/miw2oXF1UHRqZLl1Ii4YZg7e+z2VIJiBhS+N8Fl93sjgboZyTNfVNuDwUQihbkfQY1WP/eapB83hb0mKz6QJw3Npds6J1VhvtEQvNoUMaoDpUobxf4y7YQueZC3duXooy5rp7aFe7lafDsj5Mm2Gf1Sd3WK7soZ2qjf+FwRF8FqXPB0FktMhhEbpWmkKfooUNKpgjSGxW4H4bt2svFX7OGKqF9fWANjdTneLR4="
  # sauce_connect: true
script:
  - echo "Test Disabled"
# - npm run test:es5
# - npm run test:es6
# - npm run test:es6-modules
before_deploy: "npm run build"
deploy:
  - provider: npm
    email: systems@author.io
    api_key: $NPM_API_KEY
    skip_cleanup: true
    on:
      tags: true
      branch: master
      tag: latest
  - provider: releases
    api_key: $GITHUB_API_KEY
    skip_cleanup: true
    overwrite: true
    file_glob: true
    files: dist/**/*
    on:
      tags: true
      branch: master
notifications:
  slack:
    rooms:
      - authorio:$SLACK_KEY#oss
    on_success: change
    on_failure: always
