language: node_js
node_js:
- 11.6.0
script:
- npm run test:es5
- npm run test:es6
- npm run test:es6-modules
before_deploy: "npm run build"
deploy:
  - provider: npm
    email: systems@author.io
    api_key: $NPM_API_KEY
    skip_cleanup: true
    on:
      tags: true
      branch: master
      tag: latest
  - provider: releases
    api_key: $GITHUB_API_KEY
    skip_cleanup: true
    overwrite: true
    file_glob: true
    files: dist/**/*
    on:
      tags: true
      branch: master
notifications:
  slack:
    rooms:
      - authorio:$SLACK_KEY#oss
    on_success: change
    on_failure: always
